- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20250130105424764600000007.czw0c2uys7jo.us-east-1.rds.amazonaws.com" 
    login_user: "marielle"
    login_password: "project19"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-20250130105424764600000007.czw0c2uys7jo.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "marielle" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "project19" }
