- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20250130105424764600000007.czw0c2uys7jo.us-east-1.rds.amazonaws.com"
    login_user: "marielle"
    login_password: "project19"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20250130105424764600000007.czw0c2uys7jo.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "marielle" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "project19" }


